# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/mapper.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13protos/mapper.proto\"Y\n\tShardData\x12\x12\n\nshard_file\x18\x01 \x01(\t\x12\r\n\x05start\x18\x02 \x01(\x05\x12\x0b\n\x03\x65nd\x18\x03 \x01(\x05\x12\x1c\n\tcentroids\x18\x04 \x03(\x0b\x32\t.Centroid\"5\n\x08\x43\x65ntroid\x12\x13\n\x0b\x63\x65ntroid_id\x18\x01 \x01(\x05\x12\t\n\x01x\x18\x02 \x01(\x01\x12\t\n\x01y\x18\x03 \x01(\x01\" \n\x0eMapperResponse\x12\x0e\n\x06result\x18\x01 \x01(\t20\n\x06Mapper\x12&\n\x07MapData\x12\n.ShardData\x1a\x0f.MapperResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.mapper_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SHARDDATA']._serialized_start=23
  _globals['_SHARDDATA']._serialized_end=112
  _globals['_CENTROID']._serialized_start=114
  _globals['_CENTROID']._serialized_end=167
  _globals['_MAPPERRESPONSE']._serialized_start=169
  _globals['_MAPPERRESPONSE']._serialized_end=201
  _globals['_MAPPER']._serialized_start=203
  _globals['_MAPPER']._serialized_end=251
# @@protoc_insertion_point(module_scope)
