# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: km.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08km.proto\x1a\x1bgoogle/protobuf/empty.proto\")\n\tDataPoint\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08\x66\x65\x61tures\x18\x02 \x03(\x02\"6\n\x0cKeyValuePair\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x19\n\x05value\x18\x02 \x01(\x0b\x32\n.DataPoint\"G\n\x12InputSplitResponse\x12\x10\n\x08split_id\x18\x01 \x01(\x05\x12\x1f\n\x0b\x64\x61ta_points\x18\x02 \x03(\x0b\x32\n.DataPoint\"c\n\x10PartitionRequest\x12\x11\n\tmapper_id\x18\x01 \x01(\x05\x12\x14\n\x0cpartition_id\x18\x02 \x01(\x05\x12&\n\x0fkey_value_pairs\x18\x03 \x03(\x0b\x32\r.KeyValuePair\"#\n\x11PartitionResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"6\n\rReduceRequest\x12\x11\n\tmapper_id\x18\x01 \x01(\x05\x12\x12\n\nreducer_id\x18\x02 \x01(\x05\"(\n\x08\x43\x65ntroid\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08\x66\x65\x61tures\x18\x02 \x03(\x02\"0\n\x10\x43\x65ntroidResponse\x12\x1c\n\tcentroids\x18\x01 \x03(\x0b\x32\t.Centroid2\x87\x01\n\x06KMeans\x12;\n\nInputSplit\x12\x16.google.protobuf.Empty\x1a\x13.InputSplitResponse0\x01\x12@\n\x13\x43\x65ntroidCompilation\x12\x16.google.protobuf.Empty\x1a\x11.CentroidResponse2r\n\x06Mapper\x12\x32\n\x03Map\x12\x13.InputSplitResponse\x1a\x16.google.protobuf.Empty\x12\x34\n\tPartition\x12\x13.InputSplitResponse\x1a\x12.PartitionResponse2o\n\x07Reducer\x12\x37\n\x0eShuffleAndSort\x12\x11.PartitionRequest\x1a\x12.PartitionResponse\x12+\n\x06Reduce\x12\x0e.ReduceRequest\x1a\x11.CentroidResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'km_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DATAPOINT']._serialized_start=41
  _globals['_DATAPOINT']._serialized_end=82
  _globals['_KEYVALUEPAIR']._serialized_start=84
  _globals['_KEYVALUEPAIR']._serialized_end=138
  _globals['_INPUTSPLITRESPONSE']._serialized_start=140
  _globals['_INPUTSPLITRESPONSE']._serialized_end=211
  _globals['_PARTITIONREQUEST']._serialized_start=213
  _globals['_PARTITIONREQUEST']._serialized_end=312
  _globals['_PARTITIONRESPONSE']._serialized_start=314
  _globals['_PARTITIONRESPONSE']._serialized_end=349
  _globals['_REDUCEREQUEST']._serialized_start=351
  _globals['_REDUCEREQUEST']._serialized_end=405
  _globals['_CENTROID']._serialized_start=407
  _globals['_CENTROID']._serialized_end=447
  _globals['_CENTROIDRESPONSE']._serialized_start=449
  _globals['_CENTROIDRESPONSE']._serialized_end=497
  _globals['_KMEANS']._serialized_start=500
  _globals['_KMEANS']._serialized_end=635
  _globals['_MAPPER']._serialized_start=637
  _globals['_MAPPER']._serialized_end=751
  _globals['_REDUCER']._serialized_start=753
  _globals['_REDUCER']._serialized_end=864
# @@protoc_insertion_point(module_scope)
