# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import mapper_pb2 as mapper__pb2


class MapperStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MapData = channel.unary_unary(
                '/Mapper/MapData',
                request_serializer=mapper__pb2.ShardData.SerializeToString,
                response_deserializer=mapper__pb2.MapperResponse.FromString,
                )
        self.Mapper2ReduceData = channel.unary_unary(
                '/Mapper/Mapper2ReduceData',
                request_serializer=mapper__pb2.SendDataRequest.SerializeToString,
                response_deserializer=mapper__pb2.MapperDataResponse.FromString,
                )


class MapperServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MapData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Mapper2ReduceData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MapperServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MapData': grpc.unary_unary_rpc_method_handler(
                    servicer.MapData,
                    request_deserializer=mapper__pb2.ShardData.FromString,
                    response_serializer=mapper__pb2.MapperResponse.SerializeToString,
            ),
            'Mapper2ReduceData': grpc.unary_unary_rpc_method_handler(
                    servicer.Mapper2ReduceData,
                    request_deserializer=mapper__pb2.SendDataRequest.FromString,
                    response_serializer=mapper__pb2.MapperDataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Mapper', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Mapper(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MapData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Mapper/MapData',
            mapper__pb2.ShardData.SerializeToString,
            mapper__pb2.MapperResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Mapper2ReduceData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Mapper/Mapper2ReduceData',
            mapper__pb2.SendDataRequest.SerializeToString,
            mapper__pb2.MapperDataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
