# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import reducer_pb2 as reducer__pb2


class ReducerStub(object):
    """Define the Reducer service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartReduce = channel.unary_unary(
                '/reducer.Reducer/StartReduce',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=reducer__pb2.ReducerResponse.FromString,
                )
        self.SendReduceData = channel.unary_unary(
                '/reducer.Reducer/SendReduceData',
                request_serializer=reducer__pb2.ReduceData.SerializeToString,
                response_deserializer=reducer__pb2.ReducerResponse.FromString,
                )


class ReducerServicer(object):
    """Define the Reducer service.
    """

    def StartReduce(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendReduceData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReducerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartReduce': grpc.unary_unary_rpc_method_handler(
                    servicer.StartReduce,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=reducer__pb2.ReducerResponse.SerializeToString,
            ),
            'SendReduceData': grpc.unary_unary_rpc_method_handler(
                    servicer.SendReduceData,
                    request_deserializer=reducer__pb2.ReduceData.FromString,
                    response_serializer=reducer__pb2.ReducerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'reducer.Reducer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Reducer(object):
    """Define the Reducer service.
    """

    @staticmethod
    def StartReduce(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/reducer.Reducer/StartReduce',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            reducer__pb2.ReducerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendReduceData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/reducer.Reducer/SendReduceData',
            reducer__pb2.ReduceData.SerializeToString,
            reducer__pb2.ReducerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
